version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://db:5432/cu_mock
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bot-network
    restart: on-failure
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=cu_mock
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cu_mock"]
      interval: 2s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - bot-network
networks:
  bot-network:
    driver: bridge
volumes:
  db-data: